export interface BaseApiResponse {
    message: string;
    success: boolean;
    statusCode: number;
}
export enum Role {
  CLINICIAN = "CLINICIAN",
  SUPERVISOR = "SUPERVISOR",
  PARTNER = "PARTNER",
  PAYROLL = "PAYROLL"
}

export enum SubmissionStatus {
  PENDING = "PENDING",
  SUPERVISOR_APPROVED = "SUPERVISOR_APPROVED",
  SUPERVISOR_REJECTED = "SUPERVISOR_REJECTED",
  PARTNER_APPROVED = "PARTNER_APPROVED",
  PARTNER_REJECTED = "PARTNER_REJECTED",
  PAYROLL_APPROVED = "PAYROLL_APPROVED",
  PAYROLL_REJECTED = "PAYROLL_REJECTED",
  COMPLETED = "COMPLETED",
}
